version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongodb

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=miniprojetmsmysql
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=pass
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8083:80
    environment:
      - PMA_HOST=mysql
      - PMA_USER=admin
      - PMA_PASSWORD=pass
  eureka:
    container_name: eureka
    build: .\eureka-server
    ports:
      - "8761:8761"
    image: "eureka"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/

volumes:
  data: {}
  mysql_data: {}

networks:
  default:
    name: mongodb_network
